#!/usr/bin/env python3
"""
make_tissue_mesh.py -- author a tissue sheet at a resolution you choose.

Run INSIDE the container:

    docker compose run --rm surrol python container/make_tissue_mesh.py
    docker compose run --rm surrol python container/make_tissue_mesh.py --size 0.08 --res 24

WHY NOT JUST USE PyBullet's DEMO CLOTH
--------------------------------------
`cloth_z_up.obj` measures 60 cm across and has 25 simulation nodes -- 15 cm
between neighbours. Three separate problems follow from that:

  1. You cannot resolve a deformation gradient with 15 cm spacing. Retraction
     produces a local strain field; at this resolution there is no field, just
     five points in a line.
  2. 60 cm is not tissue. Surgical retraction happens over a few centimetres,
     and getting the length scale wrong makes every stiffness and force number
     meaningless even as a relative comparison.
  3. The demo asset's render mesh has a different vertex count from its
     simulation mesh, so PyBullet's node ordering cannot be matched back to the
     .obj topology. That means no mesh connectivity, which means no graph
     network later.

Authoring the mesh here solves all three: you pick the size and resolution, and
because the file has exactly one vertex per simulation node, the topology maps
cleanly and gets stored in every trajectory.

RESOLUTION IS A REAL TRADE-OFF
------------------------------
Cost grows as res^2 in nodes and worse in solver time. A 20x20 sheet is 400
nodes, which simulates comfortably and is enough to see a strain field. Going
to 50x50 is 2500 nodes and will be noticeably slow in PyBullet -- that is the
point at which the MPM/Taichi path starts to pay for itself.

OUTPUT FORMAT
-------------
Wavefront .obj: a plain-text list of vertices (`v x y z`) and triangles
(`f i j k`, 1-indexed). Deliberately the simplest possible format -- you can
open it in a text editor and read it.
"""

import argparse
import os


def build_grid(size: float, res: int, height: float):
    """A flat square sheet in the xy plane, centred on the origin at z=height.

    Returns (vertices, triangles) with 0-indexed triangles.
    """
    if res < 2:
        raise ValueError("res must be at least 2")

    step = size / (res - 1)
    half = size / 2.0

    # Row-major node ordering: index(i, j) = i * res + j, with i along y and
    # j along x. Keeping this explicit matters -- the ordering here is the
    # ordering your dynamics model will see, and it has to stay consistent.
    verts = []
    for i in range(res):
        for j in range(res):
            verts.append((-half + j * step, -half + i * step, height))

    # Each grid cell becomes two triangles. Winding is kept consistent
    # (counter-clockwise seen from +z) so surface normals all point the same
    # way; inconsistent winding makes contact and rendering behave strangely.
    tris = []
    for i in range(res - 1):
        for j in range(res - 1):
            a = i * res + j
            b = a + 1
            c = a + res
            d = c + 1
            tris.append((a, b, d))
            tris.append((a, d, c))
    return verts, tris


def write_obj(path: str, verts, tris, comment: str = "") -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w") as f:
        f.write("# tissue sheet generated by make_tissue_mesh.py\n")
        if comment:
            f.write(f"# {comment}\n")
        for x, y, z in verts:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for a, b, c in tris:
            # .obj indices are 1-based.
            f.write(f"f {a+1} {b+1} {c+1}\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--size", type=float, default=0.10,
                    help="edge length in METRES (default 0.10 = 10 cm, a "
                         "plausible surgical field)")
    ap.add_argument("--res", type=int, default=20,
                    help="nodes per side (default 20 -> 400 nodes)")
    ap.add_argument("--height", type=float, default=0.05,
                    help="z position of the sheet in metres")
    ap.add_argument("--out", default="",
                    help="output path (default /work/assets/tissue_<res>x<res>.obj)")
    args = ap.parse_args()

    out = args.out or f"/work/assets/tissue_{args.res}x{args.res}.obj"
    verts, tris = build_grid(args.size, args.res, args.height)
    spacing = args.size / (args.res - 1)
    write_obj(out, verts, tris,
              f"size={args.size}m res={args.res} spacing={spacing:.4f}m")

    print(f"wrote {out}")
    print(f"  {len(verts)} vertices, {len(tris)} triangles")
    print(f"  {args.size*100:.1f} cm square, {spacing*1000:.1f} mm between nodes")
    print(f"  resting at z = {args.height:.3f} m")
    if len(verts) > 1600:
        print("  NOTE: above ~1600 nodes PyBullet's mass-spring solver gets "
              "slow.\n        That is the point to consider the Taichi/MPM path.")


if __name__ == "__main__":
    main()
