#!/usr/bin/env python3
"""energy_audit.py -- does MPM dissipation count transfers, or count seconds?

Run on the HOST (Taichi/Metal, see CLAUDE.md):

    conda activate tissue-host
    python host/energy_audit.py --selftest             # the instrument, ~1 min
    python host/energy_audit.py                        # cells 1, 3, 4
    python host/energy_audit.py --cells 1 --materials soft --frames 12   # quick

THE QUESTION THIS ANSWERS
-------------------------
DECISION_LOG.md section 9.6 concluded that MPM's particle-grid transfers dissipate
energy PER TRANSFER rather than per unit of simulated time, and therefore that
refining the substep at a fixed grid cannot converge. That conclusion is now
load-bearing: CLAUDE.md tells future work not to refine, and section 9.6 uses it to
declare safety_strain non-comparable between episodes.

It rests on one probe -- specific kinetic energy of a 3,000-particle subset at a
fixed simulated time, falling monotonically across the sweep
(substep_study.py:216) -- and that probe cannot carry it:

  * KE IS NOT THE BUDGET. The rows settled under gravity, so KE was pumped by
    gravitational release and drained by contact, elasticity and the transfers
    at once. A falling KE is equally consistent with "damped harder" and
    "converted to strain energy sooner". Psi and PE were never measured.
  * CONTACT WAS LIVE THROUGHOUT. Every row sat on the floor, so the `*= 0.1`
    band and the `bound = 3` wall condition were both firing.
  * THE FINEST ROW WAS THE REFERENCE, while being, by section 9.6's own argument,
    the most over-damped row in the sweep.
  * THE SUBSET WAS THE WRONG SET. mpm_adapter rule 2 already says so for
    safety_strain, and it is equally true of an energy.

There is also a specific reason to suspect the attribution is BACKWARDS. The
`*= 0.1` floor band (mpm3d.py:274-276) multiplies grid velocity once per substep
with no dt scaling -- that is the literal definition of a transfer-count sink,
far more obviously than the P2G/G2P round trip. Section 9.6 dismissed it because
the band touches [0] and [1] and never [2], yet the stiff material's VERTICAL
error was the largest in the sweep at 61.7%. That material has lambda/mu = 754.
Near incompressibility, suppressing lateral flow at the base suppresses vertical
settling almost rigidly, so the material with the strongest coupling showing the
largest vertical error is what the floor hypothesis PREDICTS. Cell 3 exists to
settle that.

WHAT IS MEASURED
----------------
The closed budget, over all 24,000 particles, in float64:

    E = KE_particle + KE_affine + Psi_elastic + PE_gravity

See src/energy_ledger.py for why the affine term is not optional and why the
existing `strain_energy_neohookean` is exactly the potential conjugate to the
solver's stress.

THE VERDICT IS ONE EXPONENT
---------------------------
Fit (total dissipation over a FIXED simulated time T) ~ dt^q.

    q ~ -1   per TRANSFER      section 9.6 confirmed; refinement cannot converge
    q ~  0   per unit TIME     section 9.6's mechanism is wrong; loss is a rate
    q ~ +1   truncation error  section 9.6 FALSIFIED; refinement does converge

q ~ +1 is a live outcome, not a strawman: if the non-affine velocity content
each transfer destroys is regenerated by inter-transfer motion of size |v|*dt,
the loss per transfer goes as dt^2 and the total over T goes as dt. The
predictions were written down before the runs; see DECISION_LOG.md section 9.7.

THREE CELLS
-----------
  1  clean   slab at the domain centre, gravity OFF, an exactly known isochoric
             initial stretch, and every stencil node provably five cells clear
             of any special region. Nothing but the transfers can remove energy.
  3  band    slab placed so its lowest stencil node sits exactly on k = 3,
             gravity off, given a lateral velocity. The `*= 0.1` sink is then
             the only boundary term firing and its dt scaling is measurable.
  4  s9.6    the section 9.6 configuration reproduced -- init_cube() as vendored,
             gravity on, floor contact -- now under the full ledger, so the old
             KE-only numbers can be re-read against a closed budget.

ONE PROCESS PER ROW
-------------------
Same constraint as the collector and the substep study, with one more constant:
Taichi bakes `dt`, `p_mass` AND `gravity` into kernels at compile time, because
Boundary() reads gravity as a plain Python global inside a @ti.func. `--child`
marks a child and, exactly like `--index` in mpm_adapter.py, makes recursion
structurally impossible -- the parent always passes it, and a process holding it
never dispatches. Children run with check=False: a diverged row is a RESULT.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
import time

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "third_party"))
sys.path.insert(0, os.path.join(REPO, "src"))
sys.path.insert(0, os.path.join(REPO, "host"))

import energy_ledger as EL                               # noqa: E402
import materials                                         # noqa: E402
from MPM.config import n_grid                            # noqa: E402  (no ti.init)

FRAME_DT = 0.0125
DX = 1.0 / n_grid
BASE_SAFETY = 0.3
# Multiples of the advisory substep COUNT. The same ladder section 9.6 swept, minus
# its 0.25x row: that one diverged at both materials and a diverged row carries
# no energy to fit. Five surviving rows over a factor of 16 is what the exponent
# is read from.
MULTIPLIERS = (0.5, 1.0, 2.0, 4.0, 8.0)
ROW_TIMEOUT_S = 1800

STRETCH = 1.2        # isochoric; matches the 1.16-1.18 peak stretch section 9.6 saw
BAND_VELOCITY = 0.02  # m/s lateral, cell 3
CELLS = (1, 3, 4)


# --------------------------------------------------------------------------
# Cell definitions -- the only place a cell's physics is written down
# --------------------------------------------------------------------------

def cell_config(cell: int) -> dict:
    if cell == 1:
        return dict(
            name="clean", gravity=0.0, assert_no_contact=True,
            # Domain centre. init_cube()'s slab is 0.3 x 0.3 x 0.05, so at the
            # centre its stencil spans indices ~19-44: sixteen clear cells from
            # the nearest special region at index 3.
            centre=[0.5, 0.5, 0.5], stretch=STRETCH, velocity=None,
            blurb="no contact, no gravity, known isochoric initial stretch")
    if cell == 3:
        # Lowest stencil node exactly on k = 3. base = int(z/dx - 0.5), so
        # z >= 3.5*dx = 54.7 mm puts base at 3; 55.5 mm leaves a little room
        # for float32. The `*= 0.1` band fires at k <= 3 and the wall condition
        # needs index < 3, so this arms the band and nothing else.
        z_bottom = 3.5 * DX + 0.0008
        return dict(
            name="band", gravity=0.0, assert_no_contact=False,
            centre=[0.5, 0.5, z_bottom + 0.025], stretch=1.0,
            velocity=[BAND_VELOCITY, 0.0, 0.0],
            blurb="floor band armed, gravity off, lateral drag only")
    if cell == 4:
        return dict(
            name="s9.6", gravity=9.8, assert_no_contact=False,
            centre=None, stretch=1.0, velocity=None,
            blurb="section 9.6 reproduced: init_cube as vendored, gravity, floor")
    raise ValueError(f"unknown cell {cell}")


# --------------------------------------------------------------------------
# Child: one row
# --------------------------------------------------------------------------

def run_row(out: str, *, cell: int, mu: float, lam: float, rho: float,
            n_substeps: int, frames: int) -> None:
    """Run one (cell, material, n_substeps) row and save its ledger series."""
    import mpm_energy as me

    cfg = cell_config(cell)
    inst = me.Instrument(mu=mu, lam=lam, rho=rho, n_substeps=n_substeps,
                         frame_dt=FRAME_DT, gravity=cfg["gravity"], quiet=True)
    inst.init_slab(centre=cfg["centre"], stretch=cfg["stretch"],
                   velocity=cfg["velocity"])

    pos_init = inst.m.F_x.to_numpy().copy()
    keys = ("ke", "ke_affine", "elastic", "gravity_pe", "total",
            "p_x", "p_y", "p_z", "l_x", "l_y", "l_z")
    series = {k: [] for k in keys}
    contact = []
    diverged, why = False, ""

    for f in range(frames + 1):
        led = inst.ledger()
        if not np.isfinite(led["total"]):
            diverged, why = True, f"non-finite energy at frame {f}"
            break
        for k in keys:
            series[k].append(led[k])
        c = inst.assert_no_contact()
        contact.append([c["min_index"], c["max_index"], float(c["ok"]),
                        c["clearance_m"], c["reach_m"]])
        if cfg["assert_no_contact"] and not (c["ok"] and c["sampling_safe"]):
            diverged, why = True, (
                f"CLEAN CELL VIOLATED at frame {f}: stencil {c['min_index']}.."
                f"{c['max_index']}, clearance {c['clearance_m']*1e3:.1f} mm vs "
                f"per-frame reach {c['reach_m']*1e3:.1f} mm")
            break
        if f < frames:
            try:
                inst.advance_frame(1)
            except Exception as e:                        # noqa: BLE001
                diverged, why = True, f"{type(e).__name__} at frame {f}"
                break

    np.savez_compressed(
        out,
        diverged=np.array(diverged), why=np.array(why),
        n_frames_done=np.array(len(series["total"])),
        pos_init=pos_init, pos_final=inst.m.F_x.to_numpy(),
        contact=np.array(contact, np.float64),
        meta=np.array(json.dumps(dict(
            cell=cell, mu=mu, lam=lam, rho=rho, n_substeps=n_substeps,
            substep_dt=inst.substep_dt, frame_dt=FRAME_DT, frames=frames,
            gravity=cfg["gravity"], p_mass=inst.p_mass, p_vol=inst.p_vol,
            dx=inst.dx, backend=inst.backend))),
        **{k: np.array(v, np.float64) for k, v in series.items()})


# --------------------------------------------------------------------------
# Child: the self tests
# --------------------------------------------------------------------------

def selftest_basic(mu: float, lam: float, rho: float, n_substeps: int) -> dict:
    """Checks 1, 2, 3 and 5 -- all share one (dt, p_mass, gravity), so one
    process can hold them. Check 4 cannot and is dispatched separately."""
    import mpm_energy as me
    r = {}
    inst = me.Instrument(mu=mu, lam=lam, rho=rho, n_substeps=n_substeps,
                         gravity=0.0, quiet=True)

    # CHECK 5 first, because it is the cheapest and everything else assumes it.
    # WHY: gravity is baked at compile time from a Python global. If setting it
    # to 0.0 did not take, the clean cell would be a body in free fall and the
    # release of potential energy would be read as negative dissipation.
    inst.init_slab(centre=[0.5, 0.5, 0.5], stretch=1.0)
    inst.advance_frame(1)
    v = inst.m.F_v.to_numpy()
    r["gravity_off"] = dict(passed=bool(np.abs(v).max() == 0.0),
                            detail=f"max|v| after one frame from rest = "
                                   f"{np.abs(v).max():.3e} m/s (must be exactly 0)")

    # CHECK 2: rigid translation. F = I so the stress is EXACTLY zero, C = 0, a
    # uniform velocity. P2G then G2P is a partition-of-unity round trip and must
    # be exact. WHY: any loss here is an instrument bug, not physics -- there is
    # nothing for the solver to dissipate.
    inst.init_slab(centre=[0.5, 0.5, 0.5], stretch=1.0, velocity=[0.1, -0.05, 0.02])
    e0 = inst.ledger()["total"]
    inst.advance_frame(1)
    e1 = inst.ledger()["total"]
    r["rigid_translation"] = dict(
        passed=bool(abs(e1 - e0) <= 1e-6 * max(e0, 1e-30)),
        detail=f"E: {e0:.9e} -> {e1:.9e}, relative change "
               f"{(e1 - e0) / max(e0, 1e-30):+.3e} (must be ~0)")

    # CHECK 3: an affine velocity field, with the stiffness switched OFF.
    # WHY: APIC exists to transfer affine fields exactly, and if it does not,
    # the loss the audit measures in the real cells is partly an APIC
    # implementation fault rather than the non-affine content it is attributed
    # to. mu and la are ti.fields, not baked constants, so they can be zeroed at
    # runtime -- and they must be, or this measures elastic dynamics instead of
    # the transfer. An antisymmetric A stays affine under advection forever
    # (v = Ax and x' = (I + dt A)x, so v is still linear in x'), which makes
    # exact conservation the correct expectation rather than an approximation.
    keep_mu, keep_la = inst.m.mu[None], inst.m.la[None]
    inst.m.mu[None], inst.m.la[None] = 0.0, 0.0
    inst.init_slab(centre=[0.5, 0.5, 0.5], stretch=1.0)
    x = inst.m.F_x.to_numpy().astype(np.float64)
    A = np.array([[0.0, 0.3, 0.0], [-0.3, 0.0, 0.0], [0.0, 0.0, 0.0]])  # traceless
    inst.m.F_v.from_numpy(((x - x.mean(axis=0)) @ A.T).astype(np.float32))
    # F_C MUST BE SET TOO, or the field is not affine as far as APIC is
    # concerned. A particle carries v_p + C_p (x - x_p); leaving C_p = 0 makes
    # the represented field piecewise CONSTANT, and the first transfer then
    # legitimately destroys the part it cannot see. The first version of this
    # check set only F_v and reported a 0.75% loss as an APIC fault.
    inst.m.F_C.from_numpy(np.broadcast_to(
        A, (inst.n_particles, 3, 3)).astype(np.float32))
    inst.ti.sync()
    e0 = inst.ledger()["total"]
    inst.advance_frame(1)
    e1 = inst.ledger()["total"]
    inst.m.mu[None], inst.m.la[None] = keep_mu, keep_la
    r["affine_velocity"] = dict(
        passed=bool(abs(e1 - e0) <= 1e-4 * max(e0, 1e-30)),
        detail=f"E: {e0:.9e} -> {e1:.9e}, relative change "
               f"{(e1 - e0) / max(e0, 1e-30):+.3e} (zero stiffness: APIC "
               f"transfers an affine field exactly, so this must be roundoff)")

    # CHECK 1: the split kernels must not change the physics.
    #
    # BIT-IDENTITY IS THE WRONG BAR, AND MEASURING IT IS HOW WE FOUND OUT. This
    # solver is not bitwise reproducible against ITSELF on Metal: P2G scatters
    # into the grid with atomic adds (mpm3d.py:180-182) and the GPU's summation
    # order varies between launches, so two runs of the VENDORED substep() from
    # a byte-identical initial state differ by ~1 float32 ulp after 8 substeps.
    # A check demanding array_equal would therefore fail forever, for a reason
    # having nothing to do with the split.
    #
    # So the noise floor is measured in the same process and the split is held
    # to it: fused-vs-split must sit within a small multiple of fused-vs-fused.
    # That is a real check -- a split that reordered the phases, dropped the
    # boundary pass or used a different dt would miss by orders of magnitude,
    # not by ulps.
    inst.init_slab(centre=[0.5, 0.5, 0.5], stretch=STRETCH)
    x0 = inst.m.F_x.to_numpy().copy()
    F0 = inst.m.F.to_numpy().copy()

    def _from_ic(stepper, n=24):
        inst.m.F_x.from_numpy(x0)
        inst.m.F.from_numpy(F0)
        inst.m.F_v.fill([0.0, 0.0, 0.0])
        inst.m.F_C.fill([[0.0] * 3] * 3)
        inst.m.F_grid_m.fill(0.0)
        inst.m.F_grid_v.fill([0.0, 0.0, 0.0])
        inst.ti.sync()
        for _ in range(n):
            stepper()
        inst.ti.sync()
        return inst.m.F_x.to_numpy().copy()

    fused = lambda: inst.m.substep(me.SCALE, me.THRESHOLD)   # noqa: E731
    a1, a2 = _from_ic(fused), _from_ic(fused)
    b1 = _from_ic(inst.substep_split)
    floor = float(np.abs(a1 - a2).max())
    delta = float(np.abs(a1 - b1).max())
    ulp = float(np.spacing(np.float32(0.5)))
    tol = max(4.0 * floor, 4.0 * ulp)
    r["split_matches_solver"] = dict(
        passed=bool(delta <= tol),
        detail=(f"over 24 substeps: fused-vs-split {delta/ulp:.1f} ulp, "
                f"solver's own run-to-run floor {floor/ulp:.1f} ulp "
                f"(tolerance {tol/ulp:.1f} ulp). The solver is NOT bitwise "
                f"reproducible against itself -- P2G uses atomic adds."))

    # CHECK 6: in the clean cell the boundary pass removes NOTHING -- measured,
    # not argued. This is the "contact and friction work" line of the budget,
    # and the honest way to report it is to show it is identically zero rather
    # than to estimate it. Boundary() with gravity off and no collider should do
    # exactly one thing, divide momentum by mass, which is energy-neutral
    # (|p|^2/2m == (1/2)m|v|^2). Anything left over is a branch firing that the
    # geometry was supposed to have excluded.
    #
    # This is also the only exercise the probed path gets. A code path with no
    # check on it drifts (CLAUDE.md), and this one exists precisely to be
    # trusted about small energy differences.
    inst.init_slab(centre=[0.5, 0.5, 0.5], stretch=STRETCH)
    recs = inst.advance_frame_probed(1)
    scale = max(max(x["ke_grid_after_p2g"] for x in recs), 1e-30)
    worst_bnd = max(abs(x["loss_boundary"]) for x in recs) / scale
    g2p = float(np.mean([x["loss_g2p"] for x in recs])) / scale
    r["boundary_inert_in_clean_cell"] = dict(
        passed=bool(worst_bnd < 1e-5),
        detail=(f"worst boundary energy change over {len(recs)} substeps is "
                f"{worst_bnd:.2e} of grid KE (must be ~0: no gravity, no "
                f"contact). Mean G2P projection loss over the same substeps: "
                f"{g2p*100:+.3f}% of grid KE per transfer."))
    return r


def selftest_transfer(n_substeps: int, rho: float, frames: int = 4) -> dict:
    """Check 4, one dt per process: the zero-stiffness transfer test.

    mu = lambda = 0, so the stress is identically zero and NO force acts on
    anything. Particles advect and their velocity field is repeatedly filtered
    through the grid. Whatever energy disappears is therefore transfer loss and
    nothing else -- this is the sharpest form of section 9.7's question, and with no
    stress there is no CFL condition, so dt can be swept freely.

    The velocity field is non-affine on purpose (a sine along z). APIC transfers
    affine fields exactly, so an affine field here would measure zero and prove
    nothing.
    """
    import mpm_energy as me
    inst = me.Instrument(mu=1e-12, lam=1e-12, rho=rho, n_substeps=n_substeps,
                         gravity=0.0, quiet=True)
    inst.init_slab(centre=[0.5, 0.5, 0.5], stretch=1.0, shear_mode=0.05)
    e0 = inst.ledger()
    inst.advance_frame(frames)
    e1 = inst.ledger()
    n_tr = n_substeps * frames
    return dict(n_substeps=n_substeps, substep_dt=inst.substep_dt,
                n_transfers=n_tr, e0=e0["total"], e1=e1["total"],
                loss=e0["total"] - e1["total"],
                loss_per_transfer=(e0["total"] - e1["total"]) / n_tr,
                sim_time=frames * FRAME_DT)


# --------------------------------------------------------------------------
# Parent: reporting
# --------------------------------------------------------------------------

def _load_row(path: str) -> dict:
    if not os.path.isfile(path):
        return {"diverged": True, "why": "no file -- child died before writing"}
    d = np.load(path, allow_pickle=False)
    meta = json.loads(str(d["meta"]))
    out = {"diverged": bool(d["diverged"]), "why": str(d["why"]), **meta}
    for k in ("ke", "ke_affine", "elastic", "gravity_pe", "total",
              "p_x", "p_y", "p_z", "l_x", "l_y", "l_z"):
        out[k] = d[k]
    out["pos_init"] = d["pos_init"]
    out["pos_final"] = d["pos_final"]
    out["contact"] = d["contact"]
    if out["total"].size < meta["frames"] + 1:
        out["diverged"] = True
        out["why"] = out["why"] or f"stopped at frame {out['total'].size - 1}"
    return out


def report_cell(cell: int, label: str, rows: list, frames: int) -> dict:
    cfg = cell_config(cell)
    good = [r for r in rows if not r["diverged"]]
    print(f"\n  {'n_sub':>6} {'substep':>10} {'E(0)':>11} {'E(T)':>11} "
          f"{'dissipated':>11} {'frac':>7} {'per-transfer':>13} "
          f"{'per-second':>11} {'wall':>7}")
    print("  " + "-" * 96)
    for r in rows:
        if r["diverged"]:
            print(f"  {r['n_substeps']:>6} {r['substep_dt']*1e6:>8.1f}us "
                  f"{'DIVERGED':>11}   {r['why'][:52]}")
            continue
        e0, eT = r["total"][0], r["total"][-1]
        loss = e0 - eT
        n_tr = r["n_substeps"] * frames
        T = frames * FRAME_DT
        r["loss"] = loss
        print(f"  {r['n_substeps']:>6} {r['substep_dt']*1e6:>8.1f}us "
              f"{e0:>11.5f} {eT:>11.5f} {loss:>11.5f} "
              f"{loss/max(abs(e0),1e-30)*100:>6.2f}% {loss/n_tr:>13.3e} "
              f"{loss/T:>11.4f} {r['wall']:>6.1f}s")

    if len(good) < 3:
        print("\n  Fewer than three rows survived; no exponent can be fitted.")
        return {"cell": cell, "label": label, "verdict": "INSUFFICIENT"}

    # THE SHARED-CLOUD ASSERTION. Every row must start from an identical
    # particle cloud or the pairwise field comparison below is meaningless.
    ref = good[0]["pos_init"]
    for r in good[1:]:
        if not np.array_equal(r["pos_init"], ref):
            raise SystemExit(
                f"FATAL: row n={r['n_substeps']} started from a different "
                "particle cloud. The refinement ladder assumes particle i is "
                "the same particle in every row, which held because Taichi's "
                "RNG is seeded 0 in every process. See section 9.5/9.6.")

    # ENERGY OVER THE WHOLE TRAJECTORY, not just the endpoint. If dissipation
    # were an endpoint artifact -- one late event rather than a steady drain --
    # these quarters would not be comparable.
    print(f"\n  Cumulative dissipation as a fraction of E(0), through the run:")
    print(f"  {'n_sub':>6} " + " ".join(f"{int(100*q):>7}%" for q in (.25, .5, .75, 1.)))
    for r in good:
        e = r["total"]
        e0 = e[0]
        qs = [(e0 - e[int(round(q * (len(e) - 1)))]) / max(abs(e0), 1e-30)
              for q in (.25, .5, .75, 1.0)]
        print(f"  {r['n_substeps']:>6} " + " ".join(f"{v*100:>7.2f}" for v in qs))

    # THE TERM-BY-TERM BREAKDOWN AT T. This is the table that connects section 9.6
    # to this one: its probe was KE alone, and KE alone is printed here next to
    # the budget it belongs to. If KE falls across the ladder while the TOTAL
    # dissipation also falls, then "KE fell, so damping rose" was reading a
    # redistribution as a loss.
    print(f"\n  Where the energy is at T = {frames * FRAME_DT:.3f} s "
          f"(section 9.6's probe was the KE column alone):")
    print(f"  {'n_sub':>6} {'KE':>11} {'KE_affine':>11} {'elastic':>11} "
          f"{'PE_grav':>11} {'TOTAL':>11}")
    for r in good:
        print(f"  {r['n_substeps']:>6} {r['ke'][-1]:>11.5f} "
              f"{r['ke_affine'][-1]:>11.5f} {r['elastic'][-1]:>11.5f} "
              f"{r['gravity_pe'][-1]:>11.5f} {r['total'][-1]:>11.5f}")

    # SUCCESSIVE PAIRS, no privileged finest row. section 9.6 measured every row
    # against its finest one while arguing that the finest was the most
    # over-damped -- which makes the reference the least trustworthy row in the
    # table. Adjacent differences do not need a reference at all: if they shrink
    # geometrically the scheme is converging on something, and the ratio names
    # the observed order.
    print(f"\n  Refinement ladder, successive pairs (no reference row):")
    print(f"  {'pair':>12} {'RMS diff':>12} {'as % of disp':>13} {'order p':>9}")
    deltas = []
    for a, b in zip(good, good[1:]):
        d = float(np.sqrt(((a["pos_final"].astype(np.float64)
                            - b["pos_final"].astype(np.float64)) ** 2).sum(axis=1).mean()))
        disp = float(np.sqrt(((b["pos_final"].astype(np.float64)
                               - b["pos_init"].astype(np.float64)) ** 2).sum(axis=1).mean()))
        deltas.append((f"{a['n_substeps']}/{b['n_substeps']}", d, disp))
    for i, (name, d, disp) in enumerate(deltas):
        # Observed order: how many times smaller this pair's difference is than
        # the previous pair's, in powers of two. Positive and roughly constant
        # is convergence at that order; zero or negative means the rows are not
        # approaching each other at all, whatever the finest one says.
        p = np.log2(deltas[i - 1][1] / d) if i > 0 and d > 0 else float("nan")
        order = f"{p:>9.2f}" if np.isfinite(p) else f"{'-':>9}"
        print(f"  {name:>12} {d * 1e3:>10.4f}mm "
              f"{d / max(disp, 1e-12) * 100:>12.2f}% {order}")

    # THE VERDICT, FROM THE DECAY RATE RATHER THAN THE LOSS FRACTION.
    #
    # WHY NOT THE FRACTION. A fraction of E(0) cannot exceed 1, and the clean
    # cell reaches 78%. Once a row is that far along, the next row cannot lose
    # proportionally more even if its dissipation is genuinely stronger, so the
    # fitted exponent is squeezed toward zero by the ceiling and not by the
    # physics. That would bias this study TOWARD its own conclusion, which is
    # the one direction a study must not be biased.
    #
    # The decay constant k = -ln(E(T)/E(0)) / T has no ceiling: it is the
    # e-folding rate, and it keeps growing however much energy is already gone.
    # Where nothing is saturated the two measures agree to two decimals (cell 4
    # loses only 1-5%, and its q_loss and q_rate match), which is what makes it
    # safe to prefer the one that also works where they do not.
    dts = np.array([r["substep_dt"] for r in good])
    losses = np.array([r["loss"] for r in good])
    T = frames * FRAME_DT
    rates = np.array([
        -np.log(max(r["total"][-1], 1e-300) / r["total"][0]) / T
        if r["total"][0] > 0 and r["total"][-1] > 0 else np.nan
        for r in good])
    fit_loss = EL.fit_scaling_exponent(dts, losses)
    fit = EL.fit_scaling_exponent(dts, rates)
    col = EL.normalisation_collapse(dts, losses, total_time=T)
    code, why = EL.verdict(fit["q"], fit["r2"], col["collapses"],
                           collapse_ratio=col["collapse_ratio"],
                           span=float(dts.max() / dts.min()))
    print(f"\n  decay rate k = -ln(E(T)/E(0))/T:  "
          + "  ".join(f"{r:.4f}/s" for r in rates))
    print(f"  k(dt) ~ dt^q:     q = {fit['q']:+.3f}   r2 = {fit['r2']:.4f}   "
          f"({fit['n']} rows, {fit['n_dropped']} dropped)   <- the verdict")
    print(f"  loss(dt) ~ dt^q:  q = {fit_loss['q']:+.3f}   "
          f"r2 = {fit_loss['r2']:.4f}   (ceiling-limited where loss is large)")
    print(f"  collapse spread (max/min, 1.0 is perfect):  "
          f"per transfer {col['spread_per_transfer']:.2f}   "
          f"per second {col['spread_per_time']:.2f}   -> {col['collapses']}")
    print(f"\n  VERDICT [{cell} {cfg['name']}, {label}]: {code}")
    print(f"    {why}")

    # MOMENTUM IS ONLY A CHECK WHERE IT IS CONSERVED. Cell 1 is closed: no
    # gravity, no contact, zero initial momentum, and nothing in the solver can
    # create any. Cells 3 and 4 have a floor and a gravity field, which exchange
    # momentum with the world by design -- reporting their nonzero momentum as
    # a fault was wrong, and the first version of this did exactly that.
    if cfg["gravity"] == 0.0 and cfg["assert_no_contact"]:
        # Relative, not absolute. The scale is the momentum the body would have
        # if all its remaining kinetic energy were one coherent translation;
        # a drift is only meaningful against that.
        worst = 0.0
        for r in good:
            p = np.hypot(np.hypot(r["p_x"][-1], r["p_y"][-1]), r["p_z"][-1])
            mass = r["p_mass"] * 24000.0
            scale = np.sqrt(2.0 * max(r["ke"][-1], 1e-30) * mass)
            worst = max(worst, p / max(scale, 1e-30))
        print(f"    linear momentum at T, worst row: {worst:.2e} of the "
              "coherent-translation scale "
              + ("(float32 noise, as it must be)" if worst < 1e-4 else
                 "(NOT noise -- the solver created momentum; investigate)"))
    return {"cell": cell, "label": label, "verdict": code, "q": fit["q"],
            "r2": fit["r2"], "collapse": col["collapses"], "why": why}


# --------------------------------------------------------------------------
# Parent: dispatch
# --------------------------------------------------------------------------

def dispatch(cmd, timeout=ROW_TIMEOUT_S):
    t0 = time.time()
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return proc.returncode, time.time() - t0, proc.stderr
    except subprocess.TimeoutExpired:
        return -1, time.time() - t0, f"timed out after {timeout}s"


def run_selftest(mu, lam, rho, n_adv, scratch) -> bool:
    print("=" * 96)
    print("SELFTEST -- the instrument, before any result from it counts".center(96))
    print("=" * 96)
    out = os.path.join(scratch, "selftest_basic.json")
    rc, wall, err = dispatch([sys.executable, os.path.abspath(__file__),
                              "--child", "selftest-basic", "--out", out,
                              "--material", f"{mu:.10g}", f"{lam:.10g}", f"{rho:.10g}",
                              "--row", str(n_adv)])
    if rc != 0 or not os.path.isfile(out):
        print(f"  basic selftest child failed (rc={rc})\n{err[-2000:]}")
        return False
    res = json.load(open(out))
    ok = True
    for name in ("gravity_off", "rigid_translation", "affine_velocity",
                 "split_matches_solver",
                 "boundary_inert_in_clean_cell"):
        c = res[name]
        ok &= c["passed"]
        print(f"  [{'PASS' if c['passed'] else 'FAIL'}] {name:<22} {c['detail']}")

    # CHECK 4, one process per dt. No stress means no CFL, so the ladder can be
    # much wider than the real cells' -- a factor of 64 here.
    print(f"\n  Zero-stiffness transfer test (mu = lambda = 0: nothing but the "
          f"transfers can\n  remove energy). If loss per transfer is flat in dt, "
          f"dissipation counts transfers.")
    print(f"  {'n_sub':>6} {'substep':>10} {'transfers':>10} {'E(0)':>12} "
          f"{'loss':>12} {'loss/transfer':>14}")
    rows = []
    for n in (4, 16, 64, 256):
        o = os.path.join(scratch, f"selftest_transfer_{n}.json")
        rc, wall, err = dispatch([sys.executable, os.path.abspath(__file__),
                                  "--child", "selftest-transfer", "--out", o,
                                  "--row", str(n), "--material", "0", "0",
                                  f"{rho:.10g}"])
        if rc != 0 or not os.path.isfile(o):
            print(f"  {n:>6}  child failed (rc={rc}): {err.strip()[-200:]}")
            continue
        r = json.load(open(o))
        rows.append(r)
        print(f"  {r['n_substeps']:>6} {r['substep_dt']*1e6:>8.1f}us "
              f"{r['n_transfers']:>10} {r['e0']:>12.6e} {r['loss']:>12.5e} "
              f"{r['loss_per_transfer']:>14.5e}")
    if len(rows) >= 3:
        dts = np.array([r["substep_dt"] for r in rows])
        loss = np.array([r["loss"] for r in rows])
        fit = EL.fit_scaling_exponent(dts, loss)
        col = EL.normalisation_collapse(dts, loss, rows[0]["sim_time"])
        code, why = EL.verdict(fit["q"], fit["r2"], col["collapses"],
                           collapse_ratio=col["collapse_ratio"])
        print(f"\n  pure-transfer loss(dt) ~ dt^q:  q = {fit['q']:+.3f}  "
              f"r2 = {fit['r2']:.4f}  -> {code}")
        print(f"    {why}")
    print(f"\n  SELFTEST {'PASSED' if ok else 'FAILED'} -- "
          + ("the instrument is sound; results below are readable."
             if ok else "do not read any result below."))
    return ok


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__.split("\n")[1],
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--frames", type=int, default=60,
                    help="recorded frames per row (60 x 12.5 ms = 0.75 s, "
                         "matching section 9.6)")
    ap.add_argument("--cells", type=int, nargs="+", default=list(CELLS),
                    choices=list(CELLS))
    ap.add_argument("--materials", default="both", choices=("both", "soft", "stiff"))
    ap.add_argument("--multipliers", type=float, nargs="+", default=None)
    ap.add_argument("--selftest", action="store_true",
                    help="run the instrument checks and stop")
    ap.add_argument("--no-selftest", action="store_true",
                    help="skip the gate (for iterating; never for a result)")
    # Child-only. Presence means "you are one row"; see the module docstring.
    ap.add_argument("--child", default=None, help=argparse.SUPPRESS)
    ap.add_argument("--out", default="", help=argparse.SUPPRESS)
    ap.add_argument("--row", type=int, default=None, help=argparse.SUPPRESS)
    ap.add_argument("--cell", type=int, default=1, help=argparse.SUPPRESS)
    ap.add_argument("--material", type=float, nargs=3, default=None,
                    help=argparse.SUPPRESS)
    args = ap.parse_args(argv)

    # THE CHILD BRANCH -- never dispatches, so recursion cannot happen.
    if args.child:
        mu, lam, rho = args.material
        if args.child == "row":
            run_row(args.out, cell=args.cell, mu=mu, lam=lam, rho=rho,
                    n_substeps=args.row, frames=args.frames)
        elif args.child == "selftest-basic":
            json.dump(selftest_basic(mu, lam, rho, args.row), open(args.out, "w"))
        elif args.child == "selftest-transfer":
            json.dump(selftest_transfer(args.row, rho), open(args.out, "w"))
        else:
            raise SystemExit(f"unknown child kind {args.child}")
        return 0

    # THE PARENT. Must not import mpm_energy or mpm3d -- that would run
    # ti.init() and compile kernels in the very process the children exist to
    # isolate. Only MPM.config (which imports nothing) is touched, at the top.
    import mpm_adapter
    mats = {s: mpm_adapter.sample_episode_material(s) for s in (0, 1)}
    by_ratio = sorted(mats.items(), key=lambda kv: kv[1][1] / kv[1][0])
    labelled = [("soft-lambda", by_ratio[0][1]), ("stiff-lambda", by_ratio[1][1])]
    if args.materials == "soft":
        labelled = labelled[:1]
    elif args.materials == "stiff":
        labelled = labelled[1:]

    print("=" * 96)
    print("MPM ENERGY AUDIT -- section 9.7".center(96))
    print("=" * 96)
    print(f"dx = 1/{n_grid} = {DX*1e3:.3f} mm, frame_dt = {FRAME_DT*1e3:.2f} ms, "
          f"{args.frames} frames = {args.frames*FRAME_DT:.3f} s per row")
    print("Budget: KE_particle + KE_affine + Psi_elastic + PE_gravity, over all "
          "24,000 particles, float64.")
    print("Verdict: the exponent q in (dissipation over fixed T) ~ dt^q.  "
          "-1 per transfer, 0 per second, +1 convergent.")

    t0 = time.time()
    scratch = tempfile.mkdtemp(prefix="energy_audit_")
    summary = []
    try:
        mu0, lam0, rho0 = labelled[0][1]
        n_adv0 = int(np.ceil(FRAME_DT / materials.suggested_substep_dt(
            mu0, rho0, DX, safety=BASE_SAFETY, lam=lam0)))
        if not args.no_selftest:
            if not run_selftest(mu0, lam0, rho0, n_adv0, scratch) and not args.selftest:
                print("\nSELFTEST FAILED -- refusing to run the cells. D1 is a gate.")
                return 1
        if args.selftest:
            return 0

        mults = tuple(args.multipliers) if args.multipliers else MULTIPLIERS
        for cell in args.cells:
            cfg = cell_config(cell)
            for label, (mu, lam, rho) in labelled:
                n_adv = int(np.ceil(FRAME_DT / materials.suggested_substep_dt(
                    mu, rho, DX, safety=BASE_SAFETY, lam=lam)))
                ns = sorted({max(1, int(round(n_adv * m))) for m in mults})
                print(f"\n{'=' * 96}")
                print(f"CELL {cell} ({cfg['name']}) -- {cfg['blurb']}")
                print(f"{label}: mu = {mu:.0f} Pa, lambda = {lam:.0f} Pa, "
                      f"rho = {rho:.1f}, lambda/mu = {lam/mu:.0f}; "
                      f"advisory {n_adv} substeps/frame at safety={BASE_SAFETY}")
                print("=" * 96)
                rows = []
                for n in ns:
                    path = os.path.join(scratch, f"c{cell}_{label}_{n:05d}.npz")
                    rc, wall, err = dispatch(
                        [sys.executable, os.path.abspath(__file__),
                         "--child", "row", "--out", path, "--cell", str(cell),
                         "--row", str(n), "--frames", str(args.frames),
                         "--material", f"{mu:.10g}", f"{lam:.10g}", f"{rho:.10g}"])
                    r = _load_row(path)
                    if rc != 0 and not r["diverged"]:
                        r["diverged"], r["why"] = True, f"child exited {rc}"
                    r.setdefault("n_substeps", n)
                    r.setdefault("substep_dt", FRAME_DT / n)
                    r["wall"] = wall
                    if r["diverged"] and not r["why"]:
                        r["why"] = err.strip().splitlines()[-1][:80] if err else "?"
                    rows.append(r)
                summary.append(report_cell(cell, label, rows, args.frames))
                for f in os.listdir(scratch):
                    if f.startswith(f"c{cell}_{label}_"):
                        os.remove(os.path.join(scratch, f))
    finally:
        for f in os.listdir(scratch):
            os.remove(os.path.join(scratch, f))
        os.rmdir(scratch)

    print(f"\n{'=' * 96}")
    print(f"{'cell':>6} {'material':>14} {'verdict':>14} {'q':>8} {'r2':>7} {'collapse':>14}")
    for s in summary:
        if s.get("q") is None:
            print(f"{s['cell']:>6} {s['label']:>14} {s['verdict']:>14}")
        else:
            print(f"{s['cell']:>6} {s['label']:>14} {s['verdict']:>14} "
                  f"{s['q']:>+8.3f} {s['r2']:>7.4f} {s['collapse']:>14}")
    print(f"\nTotal wall time: {time.time() - t0:.1f}s")
    print("Record the outcome in DECISION_LOG.md section 9.7, and amend section 9.6 to "
          "match.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
