"""energy_ledger.py -- the closed mechanical-energy budget of an MPM state.

numpy only, so it imports on both sides (CLAUDE.md, `src/` rule). The Taichi
half of this instrument lives in host/mpm_energy.py; everything here is
arithmetic on arrays that have already left the GPU, which is what makes it
testable without a Metal device.

WHY THIS FILE EXISTS
--------------------
DECISION_LOG.md section 9.6 concluded that MPM's particle-grid transfers dissipate
energy PER TRANSFER rather than per unit of simulated time, and that a substep
refinement therefore cannot converge. That conclusion rests on one probe:
specific kinetic energy of a 3,000-particle subset at a fixed simulated time
(substep_study.py:216), measured while the tissue was settling under gravity
onto a floor whose friction law is itself un-scaled by dt.

Kinetic energy is not the budget. Under gravity it is pumped by gravitational
release and drained by contact, elasticity and the transfers at the same time,
so a falling KE is equally consistent with "damped harder" and "converted to
strain energy sooner". Section 9.7 replaces that inference with a measurement, and
this file is the measurement's arithmetic.

THE BUDGET
----------
Total mechanical energy is a state function of what the solver already holds:

    E = KE_particle + KE_affine + Psi_elastic + PE_gravity

    KE_particle = sum_p  (1/2) m |v_p|^2                    from F_v
    KE_affine   = sum_p  (1/2) m tr(C_p D C_p^T)            from F_C
    Psi_elastic = sum_p  p_vol * Psi(F_p)                   from F
    PE_gravity  = sum_p  m g z_p                            from F_x

TWO THINGS MAKE THIS EXACT RATHER THAN APPROXIMATE, and both are easy to get
quietly wrong:

1. THE ENERGY MUST BE THE ONE CONJUGATE TO THE IMPLEMENTED STRESS. mpm3d.py:165
   computes the Kirchhoff stress as

       tau = mu*(F F^T - I) + lambda*log(J)*I

   and `tissue_metrics.strain_energy_neohookean` is

       Psi = (mu/2)(I1 - 3) - mu*log(J) + (lambda/2)(log J)^2

   These are conjugate: tau = (dPsi/dF) F^T, exactly, with no small-strain
   assumption. So the energy already in the repository is the right one and no
   second energy function should be written. `kirchhoff_stress` below is the
   solver's expression transcribed, and tests/test_mpm_energy.py differentiates
   Psi numerically and checks the identity holds. If someone ever swaps the
   constitutive model in mpm3d.py without swapping Psi, that test goes red and
   the whole ledger stops being a ledger.

2. THE AFFINE TERM IS NOT OPTIONAL. This is an APIC solver: each particle
   carries an affine velocity field v_p + C_p (x - x_p) over its own volume, and
   the C part holds real kinetic energy that no sum over F_v can see. Leave it
   out and energy parked in C reads as dissipation -- which would produce
   exactly the false positive section 9.7 exists to rule out.

       KE_affine = (1/2) m tr(C D C^T),   D = (dx^2 / 4) I

   D is the second moment of the quadratic B-spline weights, the same constant
   the solver's own G2P assumes: `new_C += 4 * weight * g_v.outer_product(dpos)
   * inv_dx` (mpm3d.py:295) is the D^-1 = 4/dx^2 scaling written out. With D
   isotropic, tr(C D C^T) collapses to (dx^2/4) * ||C||_F^2.

WHAT THE VERDICT TURNS ON
-------------------------
One exponent. Fit

    (total dissipation over a FIXED simulated time T)  ~  dt^q

    q ~ -1   dissipation is per TRANSFER      -> section 9.6 confirmed, and refining
                                                dt cannot converge
    q ~  0   dissipation is per unit TIME     -> section 9.6's mechanism is wrong;
                                                the loss is a rate, not a count
    q ~ +1   dissipation is truncation error  -> section 9.6 is FALSIFIED; refinement
                                                does converge and the KE trend it
                                                saw was the gravity/contact
                                                confound

q ~ +1 is a live outcome, not a strawman. If the non-affine velocity content
each transfer destroys is regenerated by inter-transfer particle motion of size
|v| dt, the loss per transfer goes as dt^2 and the total over T goes as dt.

The exponent is reported next to a scale-free collapse diagnostic, because
section 9.6's own retrospective says a magnitude threshold got the verdict wrong
once: whichever normalisation (per transfer, per unit time) has the smaller
spread across the ladder names the mechanism without anyone choosing a cutoff.
"""

from __future__ import annotations

from typing import Dict, Optional, Sequence, Tuple

import numpy as np

ArrayLike = np.ndarray

# Second moment of the quadratic B-spline weights, as a multiple of dx^2. The
# solver hardcodes its inverse (4 * inv_dx in G2P, mpm3d.py:295); named here so
# the two can be compared rather than each carrying an anonymous 4.
QUADRATIC_D_COEFF = 0.25

# Verdict bands on the fitted exponent.
#
# THE BANDS ARE NARROW AND THE GAPS ARE REAL. A fit landing between two
# mechanisms must say so rather than be rounded into the nearer one -- and the
# first version of this file got that wrong in a way worth recording: with
# Q_PER_TRANSFER = -0.5 it filed a measured q = -0.34 as "dissipation is
# essentially independent of dt", when across that ladder the decay rate had in
# fact moved by a factor of 2.5. Asserting independence from a number that is
# not independent is precisely the overstatement section 9.7 exists to correct, so
# the verdict now quotes the measured factor and reserves RATE_LIKE for
# exponents small enough that the claim is true.
Q_PER_TRANSFER = -0.75     # q at or below this: dissipation counts transfers
Q_RATE_LIKE = 0.15         # |q| at or below this: dissipation really is a rate
Q_CONVERGENT = 0.75        # q at or above this: dissipation vanishes with dt


# --------------------------------------------------------------------------
# The four terms
# --------------------------------------------------------------------------

def kinetic_energy(vel: ArrayLike, p_mass: float) -> float:
    """Translational kinetic energy of the particles, joules.

    `vel` is (N, 3). Uniform particle mass, which is what the solver assumes:
    p_mass is a module-level scalar baked into the P2G kernel (mpm3d.py:172).
    """
    v = np.asarray(vel, np.float64)
    _require_shape(v, (None, 3), "vel")
    return float(0.5 * p_mass * np.einsum("ij,ij->", v, v))


def affine_kinetic_energy(C: ArrayLike, p_mass: float, dx: float) -> float:
    """Kinetic energy held in the APIC affine field, joules.

    `C` is (N, 3, 3) -- the solver's F_C. See the module docstring: omitting
    this term makes energy stored in C look like dissipation, which is the one
    false positive this study cannot afford.
    """
    c = np.asarray(C, np.float64)
    _require_shape(c, (None, 3, 3), "C")
    d = QUADRATIC_D_COEFF * dx * dx
    return float(0.5 * p_mass * d * np.einsum("ijk,ijk->", c, c))


def elastic_energy(F: ArrayLike, mu: float, lam: float, p_vol: float) -> float:
    """Stored Neo-Hookean strain energy, joules.

    Delegates the density to `tissue_metrics.strain_energy_neohookean` rather
    than restating it -- that function is the conjugate of the solver's stress
    and having two copies is how the two would drift apart. p_vol is the
    REFERENCE volume per particle, which is what Psi is per unit of.
    """
    from tissue_metrics import strain_energy_neohookean
    psi = strain_energy_neohookean(np.asarray(F, np.float64), mu, lam)
    return float(p_vol * psi.sum())


def gravitational_pe(pos: ArrayLike, p_mass: float, gravity: float,
                     axis: int = 2, datum: float = 0.0) -> float:
    """Gravitational potential energy, joules, relative to `datum`.

    axis=2 because the vendored solver applies gravity to F_grid_v[I][2]
    (mpm3d.py:215, the "pybullet" branch -- the taichi Y-up line above it is
    commented out). Hardcoding z here without naming that would be exactly the
    convention bug CLAUDE.md warns about.

    The datum is arbitrary and cancels in every difference, which is the only
    way this term is ever used.
    """
    x = np.asarray(pos, np.float64)
    _require_shape(x, (None, 3), "pos")
    return float(p_mass * gravity * (x[:, axis] - datum).sum())


def kirchhoff_stress(F: ArrayLike, mu: float, lam: float) -> np.ndarray:
    """The solver's stress expression, transcribed from mpm3d.py:165.

    Here so tests/test_mpm_energy.py can check that it really is the derivative
    of `strain_energy_neohookean`. NOT used by the ledger -- the ledger needs
    the energy, not the stress. If this and the solver ever disagree, the
    ledger's central assumption is void and the test says so.
    """
    f = np.asarray(F, np.float64)
    _require_shape(f, (None, 3, 3), "F")
    J = np.linalg.det(f)
    if np.any(J <= 0.0):
        raise ValueError(
            f"{int(np.count_nonzero(J <= 0.0))} of {J.size} elements have "
            "det(F) <= 0; log(J) is undefined and the solver has diverged.")
    I = np.eye(3)
    return (mu * (f @ np.swapaxes(f, -1, -2) - I)
            + lam * np.log(J)[:, None, None] * I)


# --------------------------------------------------------------------------
# The ledger
# --------------------------------------------------------------------------

def energy_ledger(pos: ArrayLike, vel: ArrayLike, C: ArrayLike, F: ArrayLike,
                  *, p_mass: float, p_vol: float, mu: float, lam: float,
                  dx: float, gravity: float = 0.0,
                  datum: float = 0.0) -> Dict[str, float]:
    """Every energy term of one solver state, plus the total and the momenta.

    Momentum is carried alongside because it is free and because it is an
    independent correctness signal: the clean cell starts with zero linear and
    zero angular momentum and no term in the solver can create either, so drift
    in them is an instrument fault that would otherwise be invisible.
    """
    x = np.asarray(pos, np.float64)
    v = np.asarray(vel, np.float64)
    ke = kinetic_energy(v, p_mass)
    ke_aff = affine_kinetic_energy(C, p_mass, dx)
    psi = elastic_energy(F, mu, lam, p_vol)
    pe = gravitational_pe(x, p_mass, gravity, datum=datum) if gravity else 0.0
    p_lin = p_mass * v.sum(axis=0)
    l_ang = p_mass * np.cross(x, v).sum(axis=0)
    return {
        "ke": ke,
        "ke_affine": ke_aff,
        "elastic": psi,
        "gravity_pe": pe,
        "total": ke + ke_aff + psi + pe,
        "p_x": float(p_lin[0]), "p_y": float(p_lin[1]), "p_z": float(p_lin[2]),
        "l_x": float(l_ang[0]), "l_y": float(l_ang[1]), "l_z": float(l_ang[2]),
    }


# --------------------------------------------------------------------------
# The verdict
# --------------------------------------------------------------------------

def fit_scaling_exponent(dt: Sequence[float],
                         loss: Sequence[float]) -> Dict[str, float]:
    """Least-squares fit of  loss ~ A * dt^q  in log-log space.

    Returns q, the prefactor, and r2. r2 is reported because a bad fit is a
    result in itself: if the points do not lie on a power law, no single
    exponent describes the dissipation and the verdict must say "ambiguous"
    rather than quote a slope nobody should trust.

    Rows with non-positive loss are dropped and counted. A negative measured
    dissipation is not noise to be averaged away -- it means energy was
    CREATED, which for this solver would be a genuine finding, so it is
    surfaced rather than swallowed.
    """
    dt = np.asarray(dt, np.float64)
    loss = np.asarray(loss, np.float64)
    if dt.shape != loss.shape:
        raise ValueError(f"dt {dt.shape} and loss {loss.shape} must match")
    good = np.isfinite(dt) & np.isfinite(loss) & (dt > 0) & (loss > 0)
    n_dropped = int((~good).sum())
    if good.sum() < 2:
        return {"q": float("nan"), "log_a": float("nan"), "r2": float("nan"),
                "n": int(good.sum()), "n_dropped": n_dropped}

    lx, ly = np.log(dt[good]), np.log(loss[good])
    q, log_a = np.polyfit(lx, ly, 1)
    resid = ly - (q * lx + log_a)
    ss_tot = ((ly - ly.mean()) ** 2).sum()
    r2 = 1.0 - (resid ** 2).sum() / ss_tot if ss_tot > 0 else 1.0
    return {"q": float(q), "log_a": float(log_a), "r2": float(r2),
            "n": int(good.sum()), "n_dropped": n_dropped}


def normalisation_collapse(dt: Sequence[float], loss: Sequence[float],
                           total_time: float) -> Dict[str, float]:
    """Which normalisation makes the ladder collapse: per transfer, or per time?

    SCALE-FREE ON PURPOSE. Section 9.6's own postmortem records that a magnitude
    threshold ("KE fell more than 10x") gave one material the wrong advice, and
    that the fix was to test a shape (monotonicity) rather than a size. Same
    idea here: the mechanism is named by whichever normalisation has the
    smaller max/min spread across the ladder, and nobody has to pick a cutoff
    for that comparison to mean something.

        per transfer:  loss / N   where N = total_time / dt
        per time:      loss / total_time

    `spread` is max/min, so 1.0 is a perfect collapse and larger is worse.
    """
    dt = np.asarray(dt, np.float64)
    loss = np.asarray(loss, np.float64)
    good = np.isfinite(dt) & np.isfinite(loss) & (dt > 0) & (loss > 0)
    if good.sum() < 2:
        return {"spread_per_transfer": float("nan"),
                "spread_per_time": float("nan"),
                "collapse_ratio": float("nan"), "collapses": "insufficient"}
    n_transfers = total_time / dt[good]
    per_transfer = loss[good] / n_transfers
    per_time = loss[good] / total_time
    s_tr = float(per_transfer.max() / per_transfer.min())
    s_ti = float(per_time.max() / per_time.min())
    # How many times tighter the winning normalisation is. 1.0 means the two
    # descriptions are equally good and the diagnostic has decided nothing.
    ratio = max(s_tr, s_ti) / max(min(s_tr, s_ti), 1e-30)
    return {"spread_per_transfer": s_tr, "spread_per_time": s_ti,
            "collapse_ratio": float(ratio),
            "collapses": "per_transfer" if s_tr < s_ti else "per_time"}


def verdict(q: float, r2: float, collapse: Optional[str] = None,
            r2_floor: float = 0.9, collapse_ratio: Optional[float] = None,
            decisive: float = 3.0,
            span: Optional[float] = None) -> Tuple[str, str]:
    """(code, one-line reason) for a fitted exponent.

    ORDER MATTERS HERE, AND GETTING IT WRONG COST TWO WRONG LABELS. The band is
    decided from q FIRST; the r2 gate can then either annotate that verdict or
    withdraw it, but it must never substitute a different one. An earlier
    version let the degenerate-fit fallback return RATE_LIKE outright whenever
    the collapse diagnostic preferred "per time", which relabelled a measured
    q = +0.24 as "independent of dt to within a few percent" -- the same
    overstatement, arriving by a second route after the first was closed.
    """
    if not np.isfinite(q):
        return "AMBIGUOUS", "no usable rows in the ladder"

    # QUOTE THE MEASURED FACTOR, NOT JUST THE BAND. Across a ladder spanning
    # `span` in dt, the per-transfer hypothesis predicts the dissipation changes
    # by `span`, and a pure rate predicts it does not change at all. Saying
    # which of those the data is near, in the same units, is worth more than any
    # label -- and it is checkable by hand from the table above it.
    measured = ""
    if span and span > 1:
        measured = (f"  Across this {span:.0f}x ladder: measured "
                    f"{span ** abs(q):.1f}x, per-transfer predicts {span:.0f}x, "
                    f"a pure rate predicts 1x.")
    if q <= Q_PER_TRANSFER:
        code, why = "PER_TRANSFER", (
            f"q = {q:+.2f}: dissipation grows nearly in proportion to the "
            "number of transfers. Refining dt cannot converge.")
    elif q >= Q_CONVERGENT:
        code, why = "CONVERGENT", (
            f"q = {q:+.2f}: dissipation vanishes as dt -> 0, which is ordinary "
            "truncation error. Refining dt DOES converge.")
    elif abs(q) <= Q_RATE_LIKE:
        code, why = "RATE_LIKE", (
            f"q = {q:+.2f}: dissipation is independent of dt to within a few "
            "percent, i.e. a rate in simulated time and not a transfer count.")
    else:
        code, why = "INTERMEDIATE", (
            f"q = {q:+.2f}: neither mechanism on its own. Dissipation "
            + ("RISES as the substep shrinks, so it is not pure truncation "
               "error, but far too weakly to be a per-transfer count."
               if q < 0 else
               "FALLS as the substep shrinks, so refinement helps, but too "
               "weakly to be clean first-order convergence."))
    why += measured

    # THE POWER-LAW GATE. An exponent read off points that do not lie on a power
    # law is a number, not a finding -- so the default is to withdraw the
    # verdict. The one exception is a series so FLAT that r2 is degenerate
    # rather than damning: with loss ~ constant there is almost no variance to
    # explain, and r2 collapses however well the description fits. "The loss did
    # not move across a factor of 64 in dt" is a strong result, not an absent
    # one, so where the scale-free collapse diagnostic is decisive the verdict
    # stands and says why it is on thinner evidence.
    if np.isfinite(r2) and r2 < r2_floor:
        if collapse_ratio is not None and collapse_ratio >= decisive and collapse:
            why += (f"  CAUTION: the power-law fit is poor (r2 = {r2:.3f}), so "
                    f"the exponent is weak evidence; the scale-free collapse "
                    f"diagnostic independently prefers '{collapse}' by "
                    f"{collapse_ratio:.0f}x.")
        else:
            return "AMBIGUOUS", (
                f"loss(dt) is not a power law (r2 = {r2:.3f} < {r2_floor}) and "
                "the collapse diagnostic does not settle it either; no single "
                "mechanism describes this ladder")

    # The collapse diagnostic only ever chooses between "per transfer" and
    # "per time", so it can confirm or contradict those two verdicts and has
    # nothing to say about the ones in between. Reporting it as a disagreement
    # with INTERMEDIATE or CONVERGENT would manufacture a conflict out of a
    # question it was never asked.
    if collapse in ("per_transfer", "per_time") and code in ("PER_TRANSFER",
                                                             "RATE_LIKE"):
        agrees = ((code == "PER_TRANSFER" and collapse == "per_transfer")
                  or (code == "RATE_LIKE" and collapse == "per_time"))
        why += ("  The collapse diagnostic agrees." if agrees else
                f"  NOTE: the collapse diagnostic prefers '{collapse}', which "
                "does not agree -- treat the verdict as provisional.")
    return code, why


# --------------------------------------------------------------------------

def _require_shape(a: np.ndarray, shape, name: str) -> None:
    if a.ndim != len(shape) or any(
            s is not None and a.shape[i] != s for i, s in enumerate(shape)):
        want = "(" + ", ".join("N" if s is None else str(s) for s in shape) + ")"
        raise ValueError(f"{name} must be {want}, got {a.shape}")
